kind: pipeline
name: delivery
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: web/Dockerfile
      repo: boulundeasv/my-web-app
      tags:
      - test
  - name: trigger update
    image: curlimages/curl
    commands:
      - 'curl -H "Authorization: Bearer mytoken" sonar.setgo.dk:7777/v1/update'