services:
  my-web-app:
    image: boulundeasv/my-web-app:test
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 7778:80
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
    command: --debug --http-api-update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7777:8080