# Use nginx base image
FROM nginx:latest

# Set working directory to nginx content directory
WORKDIR /usr/share/nginx/html

# Copy current directory contents into the container at /usr/share/nginx/html
COPY ./web .
